apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: group4-app
    app.kubernetes.io/instance: group4-app-instance
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: group4-app
spec:
  selector:
    app: group4-app
  type: NodePort
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000
      
